apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sfc-backend
  name: sfc-backend
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: sfc-backend
  type: ClusterIP
status:
  loadBalancer: {}
