apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sfc-frontend
  name: sfc-frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    appProtocol: http
  selector:
    app: sfc-frontend
  type: LoadBalancer
status:
  loadBalancer: {}
