apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sfc-frontend
  name: sfc-frontend
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: sfc-frontend
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
