apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: sfc-app-frontend
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.deployNamespace }}.sfc-app-frontend.istio.eficode.academy
